#!/bin/bash
# Auto-commit helper. Called after each queue step.
# Usage: auto_commit.sh "step description" path1 path2 ...
set -uo pipefail  # not -e — push failure should not kill the queue

cd /home/irteam/ws/alpamayo_pruning_share
DESC="${1:-progress update}"
shift || true
if [ "$#" -gt 0 ]; then
    git add "$@" 2>/dev/null || true
fi
# Always also stage logs/* and STATUS.md if dirty
git add scripts/logs/*.json scripts/logs/*.csv scripts/logs/*.png STATUS.md 2>/dev/null || true

# Commit only if there's something staged
if git diff --staged --quiet; then
    echo "[auto-commit] nothing to commit"
    exit 0
fi

git commit -m "$(cat <<EOF
Auto-queue: $DESC

Generated by run_sequential_queue.sh. See STATUS.md for current
experiment progress.

Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>
EOF
)" --no-verify 2>&1 | tail -3

git push 2>&1 | tail -2 || echo "[auto-commit] push failed (will retry next step)"
