"""Regenerate STATUS.md from current contents of scripts/logs/.

Called by the sequential queue after each step. Pulls all eval/pilot
JSONs and renders a markdown summary so the user can see at-a-glance
what's been run and what the numbers look like.
"""
from __future__ import annotations

import json
from pathlib import Path

LOG_DIR = Path(__file__).resolve().parent / "logs"
STATUS_PATH = Path(__file__).resolve().parent.parent / "STATUS.md"


def fmt_float(x, decimals=3):
    if x is None:
        return "—"
    try:
        return f"{float(x):.{decimals}f}"
    except (ValueError, TypeError):
        return str(x)


def load_eval_jsons(pattern):
    out = []
    for p in sorted(LOG_DIR.glob(pattern)):
        try:
            with open(p) as f:
                d = json.load(f)
            d["__path"] = str(p.relative_to(LOG_DIR.parent.parent))
            out.append(d)
        except Exception as e:
            print(f"[warn] {p}: {e}")
    return out


def render_eval_table(rows, title):
    lines = [f"### {title}", ""]
    lines.append("| label | drop | L2 avg | L2 3s | align | path |")
    lines.append("|---|---:|---:|---:|---:|---|")
    for r in rows:
        label = Path(r["__path"]).stem.replace("eval15_", "1.5/").replace("evalR1_", "R1/")
        n_drop = r.get("n_dropped", len(r.get("dropped_layers", [])))
        lines.append(f"| {label} | {n_drop} | {fmt_float(r.get('L2_avg'))} | "
                     f"{fmt_float(r.get('L2_3s'))} | "
                     f"{fmt_float(r.get('alignment_match_rate'))} | `{r['__path']}` |")
    lines.append("")
    return "\n".join(lines)


def render_progsort(merged_json, k_evals, title):
    lines = [f"### {title}", ""]
    lines.append("| k | dropped | L2 avg | align |")
    lines.append("|---:|---|---:|---:|")
    for ev in k_evals:
        d = ev
        k = len(d.get("dropped_layers", []))
        dropped = d.get("dropped_layers", [])
        lines.append(f"| {k} | {dropped} | {fmt_float(d.get('L2_avg'))} | "
                     f"{fmt_float(d.get('alignment_match_rate'))} |")
    lines.append("")
    return "\n".join(lines)


def render_pilot(merged_path, title):
    try:
        with open(merged_path) as f:
            d = json.load(f)
    except Exception:
        return ""
    lines = [f"### {title}", ""]
    lines.append(f"- baseline match rate: **{fmt_float(d.get('baseline_mean'))}** "
                 f"(spread {fmt_float(d.get('baseline_spread'), 4)})")
    pol = d.get("policy", {})
    lines.append(f"- KEEP ({len(pol.get('keep', []))}): {pol.get('keep', [])}")
    lines.append(f"- NEUTRAL ({len(pol.get('neutral', []))}): {pol.get('neutral', [])}")
    lines.append(f"- HARMFUL ({len(pol.get('harmful', []))}): {pol.get('harmful', [])}")
    lines.append("")
    return "\n".join(lines)


def render_greedy(greedy_path, title):
    try:
        with open(greedy_path) as f:
            d = json.load(f)
    except Exception:
        return ""
    lines = [f"### {title}", ""]
    lines.append(f"- baseline align: {fmt_float(d.get('baseline_align'))}")
    lines.append(f"- final drop set: {d.get('final_drop_set', [])}")
    lines.append("")
    lines.append("| round | added ℓ | drop set | align |")
    lines.append("|---:|---:|---|---:|")
    for h in d.get("history", []):
        r = h.get("round")
        if r == 0:
            continue
        lines.append(f"| {r} | {h.get('best_layer')} | {h.get('drop_set')} | "
                     f"{fmt_float(h.get('best_align'))} |")
    lines.append("")
    return "\n".join(lines)


def render():
    md = []
    md.append("# Experiment status")
    md.append("")
    md.append("Auto-generated by `scripts/update_status.py` after every")
    md.append("queue step. Re-read by the user from GitHub to track progress")
    md.append("while machine is unattended.")
    md.append("")
    md.append("**Direction:** alignment-grounded VLM pruning for driving VLAs.")
    md.append("Per-layer CoT-Action alignment delta (single-layer identity-bypass)")
    md.append("yields a per-layer importance score; policies are tested via L2 +")
    md.append("alignment eval on nuScenes val.")
    md.append("")
    md.append("Companion file: `PAPER_DIRECTIONS.md` — Section 0 holds the")
    md.append("refined direction and the pilot results addendum.")
    md.append("")

    # Pilot signal
    md.append("## Per-layer importance pilots (100 calib samples)")
    md.append(render_pilot(LOG_DIR / "pilot15_merged.json", "Alpamayo 1.5 (Cosmos-Reason2)"))
    md.append(render_pilot(LOG_DIR / "pilotR1_merged.json", "Alpamayo R1 (vanilla Qwen3VL)"))
    md.append("Figure: `scripts/logs/compare_r1_v15_per_layer.png`")
    md.append("")

    # Headline policy evals
    md.append("## Policy evals (zero-shot, 100 nuScenes val)")
    md.append(render_eval_table(load_eval_jsons("eval15_*.json"),
                                 "Alpamayo 1.5 — alignment-grounded policies"))
    md.append(render_eval_table(load_eval_jsons("evalR1_*.json"),
                                 "Alpamayo R1 — alignment-grounded policies"))

    # Progressive sorted
    md.append("## Progressive sorted (drop in importance-ascending order)")
    p15 = load_eval_jsons("progsort15_k*.eval.json")
    pr1 = load_eval_jsons("progsortr1_k*.eval.json")
    md.append(render_progsort(LOG_DIR / "progsort15.json", p15, "Alpamayo 1.5"))
    md.append(render_progsort(LOG_DIR / "progsortR1.json", pr1, "Alpamayo R1"))

    # Iterative greedy
    md.append("## Iterative-greedy (re-measure after each layer added)")
    md.append(render_greedy(LOG_DIR / "greedy15.json", "Alpamayo 1.5 (50 calib samples)"))
    md.append(render_greedy(LOG_DIR / "greedyR1.json", "Alpamayo R1 (50 calib samples)"))

    # Stage 2 v2 trained
    s2_evals = load_eval_jsons("eval_stage2_v2*.json")
    if s2_evals:
        md.append("## Stage 2 v2 (Expert-only LoRA on pruned base)")
        md.append(render_eval_table(s2_evals, "L2 recovery + alignment"))

    md.append("---")
    md.append("Last update: see commit timestamp.")
    return "\n".join(md)


def main():
    md = render()
    with open(STATUS_PATH, "w") as f:
        f.write(md)
    print(f"Wrote {STATUS_PATH} ({len(md)} bytes)")


if __name__ == "__main__":
    main()
